// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMS5OP1SFlFrmG-5wxZ5N3_9-QS4w4ezo',
    appId: '1:228844822963:web:cd352ec0ef80355dfcebc6',
    messagingSenderId: '228844822963',
    projectId: 'prakflutterfirebase-5d83d',
    authDomain: 'prakflutterfirebase-5d83d.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-5d83d.appspot.com',
    measurementId: 'G-LX3Z4SDWJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA48b9G0M-RYvyhJ6wBKlST5qYgO6sO3Pg',
    appId: '1:228844822963:android:e576d4a48d3accc2fcebc6',
    messagingSenderId: '228844822963',
    projectId: 'prakflutterfirebase-5d83d',
    storageBucket: 'prakflutterfirebase-5d83d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtOyy-Jg18z5WTNVpKsw4tHHyCBa-pex4',
    appId: '1:228844822963:ios:7616d190016ebe86fcebc6',
    messagingSenderId: '228844822963',
    projectId: 'prakflutterfirebase-5d83d',
    storageBucket: 'prakflutterfirebase-5d83d.appspot.com',
    iosBundleId: 'com.example.praktek6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtOyy-Jg18z5WTNVpKsw4tHHyCBa-pex4',
    appId: '1:228844822963:ios:7616d190016ebe86fcebc6',
    messagingSenderId: '228844822963',
    projectId: 'prakflutterfirebase-5d83d',
    storageBucket: 'prakflutterfirebase-5d83d.appspot.com',
    iosBundleId: 'com.example.praktek6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMS5OP1SFlFrmG-5wxZ5N3_9-QS4w4ezo',
    appId: '1:228844822963:web:374ef784299f93adfcebc6',
    messagingSenderId: '228844822963',
    projectId: 'prakflutterfirebase-5d83d',
    authDomain: 'prakflutterfirebase-5d83d.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-5d83d.appspot.com',
    measurementId: 'G-7P66LDT4C7',
  );
}
